export const estudiantes = [
  {
    id: 1,
    matricula: "ep00241",
    nombre: "Brandon David Rivera Jerez",
    responsable: "Charles Morgado",
    pais: "Colombia",
  },
  {
    id: 2,
    matricula: "ep00242",
    nombre: "Bryan Boanerges Viana Pallo",
    responsable: "Edgar Trujillo",
    pais: "Ecuador",
  },
  {
    id: 3,
    matricula: "ep00243",
    nombre: "Diego Rolando Revollo Rospigliozi",
    responsable: "Alfredo Isnado",
    pais: "Bolivia",
  },
  {
    id: 4,
    matricula: "ep00244",
    nombre: "Doull Stanley Orellena David",
    responsable: "Jose Morales",
    pais: "Honduras",
  },
  { 
    id: 5,
    matricula: "ep00245",
    nombre: "Esmeralda Hernandez Lara",
    responsable: "David Vilchis",
    pais: "Mexico",
  },
  {
    id: 6,
    matricula: "ep00246",
    nombre: "Fransico Manuel Piedrahita Torres",
    responsable: "Dorlan Merino",
    pais: "Colombia",
  },
  {
    id: 7,
    matricula: "ep00248",
    nombre: "Hector Jose Landaez Garcia",
    responsable: "Julio Lazcano ",
    pais: "Ecuador",
  },
  {
    id: 8,
    matricula: "ep00249",
    nombre: "Jaime Eduardo Romero del Toro",
    responsable: "Dorlan Merino",
    pais: "Colombia",
  },
  {
    id: 9,
    matricula: "ep00250",
    nombre: "Jonathan Stiven Litardo Chamba",
    responsable: "Julio Peque",
    pais: "Mexico",
  },
  {
    id: 10,
    matricula: "ep00251",
    nombre: "Kevin Alexander Villacreses Jimenez",
    responsable: "Julio Lazcano",
    pais: "Ecuador",
  },
  {
    id: 11,
    matricula: "ep00252",
    nombre: "Leonardo Alexander Junior Salcedo Ysaci",
    responsable: "Jhossimar Condort",
    pais: "Peru",
  },
  {
    id: 12,
    matricula: "ep00253",
    nombre: "Michael Kevin Velasquez Estupiñan",
    responsable: "Julio Lazcano",
    pais: "Mexico",
  },
  {
    id: 13,
    matricula: "ep00254",
    nombre: "Miguel Angel Amador Cepeda",
    responsable: "Jose Morales",
    pais: "Honduras",
  },
  { id: 14,
    matricula: "ep00255",
    nombre: "Nicky Steward Subuyu Lopez",
    responsable: "Julio Peque",
    pais: "Guatemala",
  },
  {
    id: 15,
    matricula: "ep00256",
    nombre: "Paolo Lucio Conza Haquehue",
    responsable: "Paul Apolaya",
    pais: "Peru",
  },
  {
    id: 16,
    matricula: "ep00257",
    nombre: "Salvador Enoc Luna Flores",
    responsable: "David Vilchis",
    pais: "Mexico",
  },
  {
    id: 17,
    matricula: "ep00258",
    nombre: "Uziel Muñoz Flores ",
    responsable: "Julio Peque",
    pais: "Mexico",
  },
  {
    id: 18,
    matricula: "ep00259",
    nombre: "Victor Brian Martin Veliz Aguado",
    responsable: "Geancarlo Marchan",
    pais: "Perú",
  },
  {
    id: 19,
    matricula: "ep00260",
    nombre: "Yesid Augusto Romero Ruiz",
    responsable: "Charles Morgado",
    pais: "Colombia",
  },
  {
    id: 20,
    matricula: "ep00261",
    nombre: "Victor Rodrigo Mollocondo Mendoza",
    responsable: "Paul Apoyala",
    pais: "Perú",
  },
  {
    id: 21,
    matricula: "ep00262",
    nombre: "Victor Neal Ramirez Beltrán",
    responsable: "Paul Apoyala",
    pais: "Perú",
  },
  {
    id: 22,
    matricula: "ep00263",
    nombre: "Ismael Pérez Aguilar",
    responsable: "Marcos Elvira",
    pais: "México",
  },
  {
    id: 23,
    matricula: "ep00225",
    nombre: "Nelson Gustavo Sanchez Sanchez",
    responsable: "Roque Zaldaña",
    pais: "El Salvador",
  },
  {
    id: 24,
    matricula: "ep00211",
    nombre: "Harol Armando Cuberos del Duca",
    responsable: "Dorian Merino",
    pais: "Colombia",
  },
  {
    id: 25,
    matricula: "ep00216",
    nombre: "Richard Armando Cuberos del Duca",
    responsable: "Dorian Merino",
    pais: "Colombia",
  },
  {
    id: 26,
    matricula: "ep00234",
    nombre: "Carlos Andres Villegas Villca",
    responsable: "Alfredo Isnado",
    pais: "Bolivia",
  },
  {
    id: 27,
    matricula: "ep00214",
    nombre: "Cesar Aogusto Serrano",
    responsable: "Rafael Piedrahita",
    pais: "Venezuela",
  },
];
