export const estudiantes = [
  {
    matricula: "ep00241",
    nombre: "Brandon David Rivera Jerez",
    responsable: "Charles Morgado",
    pais: "Colombia",
  },
  {
    matricula: "ep00242",
    nombre: "Bryan Boanerges Viana Pallo",
    responsable: "Edgar Trujillo",
    pais: "Ecuador",
  },
  {
    matricula: "ep00243",
    nombre: "Diego Rolando Revollo Rospigliozi",
    responsable: "Alfredo Isnado",
    pais: "Bolivia",
  },
  {
    matricula: "ep00244",
    nombre: "Doull Stanley Orellena David",
    responsable: "Jose Morales",
    pais: "Honduras",
  },
  {
    matricula: "ep00245",
    nombre: "Esmeralda Hernandez Lara",
    responsable: "David Vilchis",
    pais: "Mexico",
  },
  {
    matricula: "ep00246",
    nombre: "Fransico Manuel Piedrahita Torres",
    responsable: "Dorlan Merino",
    pais: "Colombia",
  },
  {
    matricula: "ep00248",
    nombre: "Hector Jose Landaez Garcia",
    responsable: "Julio Lazcano ",
    pais: "Ecuador",
  },
  {
    matricula: "ep00249",
    nombre: "Jaime Eduardo Romero del Toro",
    responsable: "Dorlan Merino",
    pais: "Colombia",
  },
  {
    matricula: "ep00250",
    nombre: "Jonathan Stiven Litardo Chamba",
    responsable: "Julio Peque",
    pais: "Mexico",
  },
  {
    matricula: "ep00251",
    nombre: "Kevin Alexander Villacreses Jimenez",
    responsable: "Julio Lazcano",
    pais: "Ecuador",
  },
  {
    matricula: "ep00252",
    nombre: "Leonardo Alexander Junior Salcedo Ysaci",
    responsable: "Jhossimar Condort",
    pais: "Peru",
  },
  {
    matricula: "ep00253",
    nombre: "Michael Kevin Velasquez Estupiñan",
    responsable: "Julio Lazcano",
    pais: "Mexico",
  },
  {
    matricula: "ep00254",
    nombre: "Miguel Angel Amador Cepeda",
    responsable: "Jose Morales",
    pais: "Honduras",
  },
  {
    matricula: "ep00255",
    nombre: "Nicky Steward Subuyu Lopez",
    responsable: "Julio Peque",
    pais: "Guatemala",
  },
  {
    matricula: "ep00256",
    nombre: "Paolo Lucio Conza Haquehue",
    responsable: "Paul Apolaya",
    pais: "Peru",
  },
  {
    matricula: "ep00257",
    nombre: "Salvador Enoc Luna Flores",
    responsable: "David Vilchis",
    pais: "Mexico",
  },
  {
    matricula: "ep00258",
    nombre: "Uziel Muñoz Flores ",
    responsable: "Julio Peque",
    pais: "Mexico",
  },
  {
    matricula: "ep00259",
    nombre: "Victor Brian Martin Veliz Aguado",
    responsable: "Geancarlo Marchan",
    pais: "Perú",
  },
  {
    matricula: "ep00260",
    nombre: "Yesid Augusto Romero Ruiz",
    responsable: "Charles Morgado",
    pais: "Colombia",
  },
  {
    matricula: "ep00261",
    nombre: "Victor Rodrigo Mollocondo Mendoza",
    responsable: "Paul Apoyala",
    pais: "Perú",
  },
  {
    matricula: "ep00262",
    nombre: "Victor Neal Ramirez Beltrán",
    responsable: "Paul Apoyala",
    pais: "Perú",
  },
  {
    matricula: "ep00263",
    nombre: "Ismael Pérez Aguilar",
    responsable: "Marcos Elvira",
    pais: "México",
  },
  {
    matricula: "ep00225",
    nombre: "Nelson Gustavo Sanchez Sanchez",
    responsable: "Roque Zaldaña",
    pais: "El Salvador",
  },
  {
    matricula: "ep00211",
    nombre: "Harol Armando Cuberos del Duca",
    responsable: "Dorian Merino",
    pais: "Colombia",
  },
  {
    matricula: "ep00216",
    nombre: "Richard Armando Cuberos del Duca",
    responsable: "Dorian Merino",
    pais: "Colombia",
  },
  {
    matricula: "ep00234",
    nombre: "Carlos Andres Villegas Villca",
    responsable: "Alfredo Isnado",
    pais: "Bolivia",
  },
  {
    matricula: "ep00214",
    nombre: "Cesar Aogusto Serrano",
    responsable: "Rafael Piedrahita",
    pais: "Venezuela",
  },
];
